### ISSUE TITLE
TensorFlow SavedModel with input/output to google cloud storage

### ISSUE THREAD

**Issue by josedonizetti** [GoogleCloudPlatform/ai-platform-samples#127]
Can we have an example of how to use google cloud storage for input/output of a TensorFlow saved model?  This is something we can do with a custom predictor (which only runs in legacy machines) but we are having a hard time migrating to a SavedModel because we can't find how to make the SavedModel read the input from a google cloud storage, and more importantly to write back the output. 

The model works with images, and pass/receive the payload base64 through the predict API is not working, because it is quite large.

**Comment by kweinmeister** [comment]
This repo is going to be archived, and we are redirecting our users to the [Vertex AI Samples repo](https://github.com/GoogleCloudPlatform/vertex-ai-samples). Please feel free to reopen this issue in that repo, if you would like to discuss it further.
