### ISSUE TITLE
Repo configuration

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/ai-platform-samples#13]
Configure PR and contributions similar as we do with Cloud ML samples.
- Bug Template
- GitHub contribution settings
- Owners group

**Comment by gogasca** [comment]
@nnegrey ping

**Comment by nnegrey** [comment]
whoops, sorry, will add.

**Comment by nnegrey** [comment]
Can you add me as an admin?

**Comment by gogasca** [comment]
done

**Comment by nnegrey** [comment]
Updated. 

Hope you don't mind, I switched over our GitHub group to admin to help assist with merges now that that is required. But feel free to switch back. :)
