### ISSUE TITLE
Hyperparameter tuning using Cloud ML hypertune for TF keras

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/ai-platform-samples#130]
Use cloudml-hypertune with TF Keras

**Comment by nicain** [comment]
@gogasca In order for an issue to be in triaged state by our team definition, an issue must have an internal assignee. I am adding you as an assignee as well as @agodi for tracking purposes.  Please reach out if you think there is a better assignee.

**Comment by kweinmeister** [comment]
This repo is going to be archived, and we are redirecting our users to the [Vertex AI Samples repo](https://github.com/GoogleCloudPlatform/vertex-ai-samples). Please feel free to reopen this issue in that repo, if you would like to discuss it further.
