### ISSUE TITLE
sklearn/structured/base/predict.py predicts all zero's

### ISSUE THREAD

**Issue by jimmy927** [GoogleCloudPlatform/ai-platform-samples#131]
**Describe the bug**

sklearn/structured/base/predict.py predicts all zero's

see here:

python  ./prediction/predict.py
[0, 0, 0]

**What sample is this bug related to?**

i-platform-samples/prediction/sklearn/structured/base/prediction/predict.py

**Source code / logs**

I did a minimal amount of changes to make it run at all:

--- a/prediction/sklearn/structured/base/prediction/predict.py
+++ b/prediction/sklearn/structured/base/prediction/predict.py
-service = googleapiclient.discovery.build('ml', 'v1')
+service = googleapiclient.discovery.build('ml', 'v1', cache_discovery=False)

**To Reproduce**

Just follow guide in proposed order.

https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/prediction/sklearn/structured/base

**Expected behavior**

Other output data than [0,0,0] for any input data.

**System Information**
**OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

It's all run on gcloud.

**Framework and version (Tensorflow, scikit-learn, XGBoost)**:

scikit-learn
0.20.4
1.15

**Python version**:

3.7

**Exact command to reproduce**:

python  ./prediction/predict.py
[0, 0, 0]

**Comment by jimmy927** [comment]
bump ?

**Comment by jimmy927** [comment]
bump^2

**Comment by kweinmeister** [comment]
This repo is going to be archived, and we are redirecting our users to the [Vertex AI Samples repo](https://github.com/GoogleCloudPlatform/vertex-ai-samples). Please feel free to reopen this issue in that repo, if you would like to discuss it further.
