### ISSUE TITLE
Launching jupyter lab using custom container 

### ISSUE THREAD

**Issue by nvrajana** [GoogleCloudPlatform/ai-platform-samples#147]
**Describe the bug**
A clear and concise description of what the bug is. Be sure to convey here whether it occurred locally or on the server (AI Platform, Google Dataflow)

I am trying to run an ai-platform notebook using a custom container. I would like to run jupyter lab inside this custom container. Do I need to specify an ENTRYPOINT in my Dockerfile like below to run jupyter lab? 

ENTRYPOINT ["jupyter lab", "--ip=0.0.0.0", "--allow-root", "--no-browser"]

I have exposed port 8080 and 8888 in my Dockerfile. 
Not sure, if this the right place to ask this question. Please let me know if I should post this somewhere else. 

**

**Comment by gogasca** [comment]
This is the right place.
Take a look at this example [here](https://github.com/GoogleCloudPlatform/ml-on-gcp/blob/master/tutorials/tensorflow/bert/start.sh)

In Dockerfile:

```
ENTRYPOINT /usr/local/bin/start.sh
```

in shell script

```
#!/bin/sh

jupyter lab --ip=0.0.0.0 --port=8080 --allow-root --no-browser --NotebookApp.token='' --NotebookApp.password=''
```

**Comment by nvrajana** [comment]
awesome.. thanks!
