### ISSUE TITLE
open jupyter lab does not point to the custom container instance

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [GoogleCloudPlatform/ai-platform-samples#155]
**Describe the bug**
I created a custom container and push it. Then I created a notebook instance using that image. When I click the "Open JupyterLab" link it does give me a jupyter notebook. So far great but this jupyter notebook is not recognizing any of the dependencies I installed through the custom container. How would I bridge this "open juypterlab" thing to use everything from my container (or maybe the jupyter version from my container).

**Comment by ethem-kinginthenorth** [comment]
ok. more on my issue. I have resolved some of the issues with a clean push. Now jupyter is started on /home/${USER} and I put a lot material to /workspace. Jupyter does not see those files under /workspace without copying under /home/${USER} - I am not sure how to control this though

**Comment by gogasca** [comment]
What is the command you use to start create the Notebook?

**Comment by ethem-kinginthenorth** [comment]
I figured this out by manipulating the default jupyter notebook configs
