### ISSUE TITLE
"OPEN JUPYTERLAB" does not show 

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [GoogleCloudPlatform/ai-platform-samples#156]
I am deriving a custom container from a non-google source. I am successfully uploading it. I have two versions of the issue:

1) if I don't have "EXPOSE 8080" in the dockerfile, then I am seeing "CONNECT" rather than "OPEN JUPYTERLAB" and when I click it I am seeing and error message indicating I need to expose 8080
2) When I add ""EXPOSE 8080" in the docerfile, then "OPEN JUPYTERLAB" shows up. But when I click it I get 504 error.

How I can resolve this issue?

**Comment by gogasca** [comment]
Using our regular containers the JupyterLab access work?

Notebooks use the Reverse Proxy to expose the JupyterLab link, this means flow is as such:

Browser <----> [  Proxy <----> Agent <---> JupyterLab ]
The agent and JupyterLab runs in the local machine.
Normally 504 means the agent can't reach the JupyterLab server. 
Can you please share the following: (Remove any sensitive data):

1. Browser logs (View -> Developer -> Developer Tools -> Console)
2. Open JupyterLab link
3. Click on Compute Engine Instances - Logs Serial Port

**Comment by ethem-kinginthenorth** [comment]
I figured out by manipulating the default jupyter config file and by exposing the required ports
