### ISSUE TITLE
Nova JupyterLab Extension cannot be installed

### ISSUE THREAD

**Issue by cidmolina** [GoogleCloudPlatform/ai-platform-samples#157]
Could not install [this repository](https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/notebooks/tools/nova-jupyterlab-extensions) on GCP Notebooks.

**I get the following error:**

jupyter@tensorflow-2-2-20200623-124019:~/ai-platform-samples/notebooks/tools/nova-jupyterlab-extensions$ sudo /opt/conda/bin/jupyter labextension install

An error occured.
ValueError: Please install Node.js and npm before continuing installation. You may be able to install Node.js from your package manager, from conda, or directly from the Node.js website (https://nodejs.org).

Manual installation of Node.js doesn't work either due to version incompatibility issues.

**Reproduction steps:**

1. start AI Platform Notebook
2. Switch to "compute engine / VM instance view"
3. SSH to respective instance
4. git clone https://github.com/GoogleCloudPlatform/ai-platform-samples.git
5. cd notebooks/tools/nova-jupyterlab-extensions
### from here we follow install instructions from the repo###
6. sudo pip3 install .
7. sudo service jupyter restart
8a. sudo jupyter labextension install (-> "jupyter not found", hence 8b)
8b. sudo /opt/conda/bin/jupyter labextension install

**Alternatives that I tried:**

- Install the repo from the Notebook itself (not SSHing to it but Opening JupyterLab from the Notebooks page).
- Upgrade JupyterLab to newest version (2.1.5).
- Using Deep Learning VM image with Tensorflow 1.15.
- Using TensorFlow:2.2 notebook instance.

None of the above worked around the issue.

**Comment by nbarraille** [comment]
I had a similar issue.
This fixed it: https://stackoverflow.com/a/59596814/488054

**Comment by matthewayne** [comment]
@cidmolina can you verify the StackOverflow question linked to by @nbarraille contained a fix for your issue?

**Comment by kweinmeister** [comment]
This tool is unmaintained and has been removed in #564.
