### ISSUE TITLE
inconsistency of the instances run in ai platform

### ISSUE THREAD

**Issue by ethem-kinginthenorth** [GoogleCloudPlatform/ai-platform-samples#170]
Here is the situation:
I push a custom container to gcr and create a notebook on ai platform. Everything I have in the dockerfile works fine. Then I stop the instance. Next day, I start it again, in this case, nvdashboard stops working and when I check out the developer tools, I am seeing a 500 error message. Somehow, on my runs after the 1st one npm or nodejs crashes.

**Comment by kweinmeister** [comment]
Hi. Is this an issue with a sample in this repo? By the way, we now have a new [GoogleCloudPlatform/vertex-ai-samples](https://github.com/GoogleCloudPlatform/vertex-ai-samples) repo.

**Comment by matthewayne** [comment]
Can you provide more context on this error? Any error messages, stack traces, your dockerfile, how you are running the container (locally, GCP, etc.), what indicators you are seeing that indicate a npm or nodejs issue or other information would help us figure out how to handle this issue.

**Comment by andrewferlitsch** [comment]
@ethem-kinginthenorth Could you provide more context on this error.

**Comment by kweinmeister** [comment]
Hi, as we haven't heard back, we'll go ahead and close the issue. Please feel free to reopen if you have more information. Thanks.
