### ISSUE TITLE
# enhance code readability in quickstart/prediction/predict.py 

### ISSUE THREAD

**Issue by singh08prashant** [GoogleCloudPlatform/ai-platform-samples#172]
Increase code readability in lines 34 & 35 of predict.py

Currently, the lines are as follows: 
 ```
name = 'projects/{}/models/{}/versions/{}'.format(PROJECT_ID, MODEL_NAME,
                                                  MODEL_VERSION)
```

Recommended changes: 
 ```
name = 'projects/{}/models/{}/versions/{}'.format(PROJECT_ID,
                                                   MODEL_NAME,
                                                   MODEL_VERSION)
```
 
or, ` name = 'projects/{}/models/{}/versions/{}'.format(PROJECT_ID, MODEL_NAME, MODEL_VERSION) `

I would like to submit a PR for this issue as my first contribution.

**Comment by kweinmeister** [comment]
Hi, are you still interested in submitting a PR for this?

**Comment by kweinmeister** [comment]
Since we haven't heard back, we will go ahead and close this issue. If you are still interested, please feel free to reopen it.

**Comment by singh08prashant** [comment]
Hi, would you consider reopening this issue again?

**Comment by kweinmeister** [comment]
Sure, are you interested in submitting a PR? If so, we can then link your PR to this issue and reopen it.
