### ISSUE TITLE
Linting errors location

### ISSUE THREAD

**Issue by vuppalli** [GoogleCloudPlatform/ai-platform-samples#177]
**Is your feature request related to a problem? Please describe.**
When linting AI Platform notebook files, the linter shows line numbers for places with issues. However, there are no line numbers present in AI Platform notebooks which makes debugging a little more difficult. Especially for misplaced parenthesis and brackets on their own line, or empty lines with whitespaces.

**Describe the solution you'd like**
It would be more helpful to also indicate which code block the error is part of and the line number within the code block for more clarity.

**Additional context**

**Comment by kweinmeister** [comment]
Good suggestion. We have implemented an improved linting process in our vertex-ai-samples repo [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/docs/contributing.md).

As we don't plan to implement changes to the CI process in this repo, I will close this issue for now.
