### ISSUE TITLE
AI platform notebooks , R, running cloudml_train() cannot find python

### ISSUE THREAD

**Issue by snowlover173** [GoogleCloudPlatform/ai-platform-samples#183]
I ran a job that had already run on RStudio a few months ago, on AI platform R notebook.

When I ran cloudml_train("training.R")

I got the following error:

[errmsg]
ERROR: (gcloud.ai-platform.jobs.submit.training) INVALID_ARGUMENT: Field: runtime_version Error: The specified runtime version '1.9' with the Python version '' is not supported or is deprecated.  Please specify a different runtime version. See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list of supported versions
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: The specified runtime version '1.9' with the Python version '' is
      not supported or is deprecated.  Please specify a different runtime version.
      See https://cloud.google.com/ml-engine/docs/runtime-version-list for a list
      of supported versions
    field: runtime_version

**Comment by snowlover173** [comment]
The successful one was run in us-central1
This one is in "australia-southeast1"

**Comment by thedriftofwords** [comment]
Can you try [passing a config file](https://tensorflow.rstudio.com/tools/cloudml/training/#training-configuration) to `cloudml_train()` to set your runtime version and Python version explicitly?

Try a newer runtime version:

```yaml
trainingInput:
  runtimeVersion: 1.15
  pythonVersion: 3.7
```

You can check [this page](https://cloud.google.com/ai-platform/training/docs/runtime-version-list) to see which Python versions to use with each runtime version.

It looks like australia-southeast1 is a [supported region for AI Platform Training](https://cloud.google.com/ai-platform/training/docs/regions#asia-pacific).

If an empty string for Python version is being passed to AI Platform by default (without using a config file), that might be an [issue to raise with RStudio](https://github.com/rstudio/cloudml/issues).

**Comment by thedriftofwords** [comment]
Hi @snowlover173, I hope that info was helpful and you got your job working again. If not, feel free to reopen this issue.
