### ISSUE TITLE
errors when using gsutils

### ISSUE THREAD

**Issue by Gibbsdavidl** [GoogleCloudPlatform/ai-platform-samples#21]
This tends to come up when using gsutil to copy large files into my workspace.

```
!gsutil  -m   cp   gs://my_bucket/fastq_from_bam/fastq_*    data
```

Errors include a 'file has changed, want to overwrite'?
Save errors, and a 504 connection error ... 
The notebook continues to run however.

<img width="695" alt="Screen Shot 2019-06-27 at 10 35 32 AM" src="https://user-images.githubusercontent.com/561865/60288217-91e38900-98c8-11e9-8e06-297bfb4b5293.png">
<img width="695" alt="Screen Shot 2019-06-27 at 10 35 51 AM" src="https://user-images.githubusercontent.com/561865/60288218-91e38900-98c8-11e9-8eeb-d6ec5944e814.png">
<img width="695" alt="Screen Shot 2019-06-27 at 10 34 24 AM" src="https://user-images.githubusercontent.com/561865/60288219-91e38900-98c8-11e9-95be-b5dd0bf2515a.png">

**Comment by gogasca** [comment]
What is the size of your Notebook instance?
What type of notebook instance are you using?
What is the total size of your files?
Maybe we can reproduce this

**Comment by Gibbsdavidl** [comment]
I'm using the 8core 16GB VM, with a python 3.5 notebook, no gpu.
There's 21 files that total about 33G,  they're between 1-3GB each for the most part.

Thanks!

**Comment by gogasca** [comment]
Will try to reproduce and get back to you. 
In the meantime can you see if you can install this plugin to monitor memory utilization:
```
https://github.com/yuvipanda/nbresuse
```
Thanks

**Comment by gogasca** [comment]
@Gibbsdavidl I was unable to reproduce (Moving a ~80GB single file), did you manage to install the plugin and monitor memory utilization? Is your bucket public? we would love to reproduce it. 

```!gsutil  -m   cp   gs://my_bucket/fastq_from_bam/fastq_*    data``` ?

**Comment by Gibbsdavidl** [comment]
Hi!  Sorry about the delay.

I just gave it another try, and *no* errors.   Must have been sun spots.  ;-)

Seemed to work fine today.

Thanks for your attention!

**Comment by gogasca** [comment]
Thanks @Gibbsdavidl please let us know if you see this issue again.
