### ISSUE TITLE
gcloud ai-platform local predict requires tensorflow even when model was trained with scikit learn 

### ISSUE THREAD

**Issue by jpchamps** [GoogleCloudPlatform/ai-platform-samples#216]
**Describe the bug**

Trying to run `gcloud ai-platform local predict` with a model trained in scikit learn but it throws an error because it did not find Tensorflow. Tensorflow is not in my env given that I am only using scikit learn. If I go to the prediction_utils.py and remove line 29 then things work. 

**Expected behavior**
code should run without Tensorflow being required given that framework is scikit learn 

**Full error here:**

> If the signature defined in the model is not serving_default then you must specify it via --signature-name flag, otherwise the command may fail.
ERROR: (gcloud.ai-platform.local.predict) b'Traceback (most recent call last):\n  File "/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 167, in main\n    from cloud.ml.prediction import prediction_lib\n  File "/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/__init__.py", line 20, in <module>\n    from .custom_code_utils import create_user_model\n  File "/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/custom_code_utils.py", line 22, in <module>\n    from .prediction_utils import PredictionError\n  File "/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 29, in <module>\n    from tensorflow.python.framework import dtypes  # pylint: disable=g-direct-tensorflow-import\nModuleNotFoundError: No module named \'tensorflow\'\n'

**To Reproduce**
1. Create env with scikit learn that does not have tensorflow 
2. Fit a model with scikit learn and save it locally, simple example:
```
from sklearn.linear_model import LogisticRegression
import numpy as np
model=LogisticRegression()
x=np.array([1,1,1,1,1,100,100,100,100,100]).reshape(-1,1)
y=['a','a','a','a','a','b','b','b','b','b']
model.fit(x,y)
joblib.dump(model,"path/model.joblib")
```
3. Save a json file called input_logistic.json to test prediction, example:
```
[1]
[100]
```
4. Run gcloud ai-platform local predict
```
gcloud ai-platform local predict --model-dir path/ \
  --json-instances path/input_logistic.json \
  --framework scikit-learn
```

**System Information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.14.6
- **Framework and version (Tensorflow, scikit-learn, XGBoost)**: scikit-learn 0.23.1
- **Python version**: 3.8.3
- **Google Cloud SDK**:312.0.0
- **Exact command to reproduce**:
```
gcloud ai-platform local predict --model-dir path/ \
  --json-instances path/input_logistic.json \
  --framework scikit-learn
```

**Comment by thedriftofwords** [comment]
Thanks for this detailed issue report!  I'm working on a fix internally, and this will help me test it. If my fix works, I'll let you know which upcoming gcloud release it will be in.

**Comment by kweinmeister** [comment]
I didn't see a TensorFlow dependency in the scikit-learn prediction sample code [here](https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/prediction/sklearn). Please let us know if there is any code in this repo we can investigate with respect to this issue.

If this issue pertains to the AI Platform service itself, then the best path forward is through [Google Cloud Support](https://cloud.google.com/support).

**Comment by kweinmeister** [comment]
Since we haven't heard back, we'll go ahead and close this issue. Please feel free to reopen if you have any more information.

**Comment by rondinif** [comment]
@kweinmeister  I would like to inform that I have encountered the same problem following the instructions given in https://cloud.google.com/ai-platform/prediction/docs/getting-started-scikit-xgboost#scikit-learn , in my `requirements.txt` 
obtained from https://cloud.google.com/ai-platform/prediction/docs/runtime-version-list ( with reference to v2.7 ) I had initially forgotten `TensorFlow==2.7.0` then runs in error: 

```
$ gcloud ai-platform local predict --model-dir $LOCAL_OR_CLOUD_STORAGE_PATH_TO_MODEL_DIRECTORY/ \
  --json-instances $LOCAL_PATH_TO_PREDICTION_INPUT_JSON \
  --framework scikit-learn
If the signature defined in the model is not serving_default then you must specify it via --signature-name flag, otherwise the command may fail.
ERROR: (gcloud.ai-platform.local.predict) b'Traceback (most recent call last):\n  File "/Users/developer/sdk/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 184, in <module>\n    main()\n  File "/Users/developer/sdk/google-cloud-sdk/lib/googlecloudsdk/command_lib/ml_engine/local_predict.py", line 167, in main\n    from cloud.ml.prediction import prediction_lib\n  File "/Users/developer/sdk/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/__init__.py", line 20, in <module>\n    from .custom_code_utils import create_user_model\n  File "/Users/developer/sdk/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/custom_code_utils.py", line 22, in <module>\n    from .prediction_utils import PredictionError\n  File "/Users/developer/sdk/google-cloud-sdk/lib/third_party/ml_sdk/cloud/ml/prediction/prediction_utils.py", line 29, in <module>\n    from tensorflow.python.framework import dtypes  # pylint: disable=g-direct-tensorflow-import\nModuleNotFoundError: No module named \'tensorflow\'\n'
```

by adding `TensorFlow==2.7.0` to `requirements.txt` and installing it solves the problem: 
```
$ pip install -r ./requirements.txt                                                               
Collecting TensorFlow==2.7.0
  Downloading tensorflow-2.7.0-cp39-cp39-macosx_10_11_x86_64.whl (207.1 MB)
..
Installing collected packages: zipp, oauthlib, requests-oauthlib, importlib-metadata, werkzeug, tensorboard-plugin-wit, tensorboard-data-server, markdown, google-auth-oauthlib, absl-py, termcolor, tensorflow-io-gcs-filesystem, tensorflow-estimator, tensorboard, opt-einsum, libclang, keras-preprocessing, keras, h5py, google-pasta, gast, flatbuffers, astunparse, TensorFlow
Successfully installed TensorFlow-2.7.0 absl-py-1.0.0 astunparse-1.6.3 flatbuffers-2.0 gast-0.4.0 google-auth-oauthlib-0.4.6 google-pasta-0.2.0 h5py-3.6.0 importlib-metadata-4.10.1 keras-2.7.0 keras-preprocessing-1.1.2 libclang-12.0.0 markdown-3.3.6 oauthlib-3.1.1 opt-einsum-3.3.0 requests-oauthlib-1.3.0 tensorboard-2.7.0 tensorboard-data-server-0.6.1 tensorboard-plugin-wit-1.8.1 tensorflow-estimator-2.7.0 tensorflow-io-gcs-filesystem-0.23.1 termcolor-1.1.0 werkzeug-2.0.2 zipp-3.7.0
```
```
$ gcloud ai-platform local predict --model-dir $LOCAL_OR_CLOUD_STORAGE_PATH_TO_MODEL_DIRECTORY/ \
  --json-instances $LOCAL_PATH_TO_PREDICTION_INPUT_JSON \
  --framework scikit-learn
If the signature defined in the model is not serving_default then you must specify it via --signature-name flag, otherwise the command may fail.
[1, 1]
```
