### ISSUE TITLE
TF Cloud requires -u parameter on AI Platform 

### ISSUE THREAD

**Issue by cpcgoogle** [GoogleCloudPlatform/ai-platform-samples#229]
In an AI Platform Notebook, the command required to install TF cloud is:
pip install -U tensorflow-cloud

Without the -U, the installation will fail.

**Comment by matthewayne** [comment]
Looks like this effects two notebooks in this repo:

- https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/notebooks/samples/optimizer/ai_platform_vizier_tuner.ipynb
- https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/notebooks/samples/optimizer/ai_platform_optimizer_multi_objective.ipynb
