### ISSUE TITLE
Notebook run build image should include tensorflow_hub

### ISSUE THREAD

**Issue by kweinmeister** [GoogleCloudPlatform/ai-platform-samples#232]
**Describe the bug**
The notebook run build failed on [PR 231](https://github.com/GoogleCloudPlatform/ai-platform-samples/pull/231) on the `import tensorflow_hub` statement.

The container should include this package to more closely replicate the AI Platform Notebook and Colab environments, both of which include this package by default. Otherwise, to pass tests, the notebook will have to unnecessarily include a `!pip install` step.

**Source code / logs**
[Build info](https://fusion.corp.google.com/runanalysis/info/prod%3Acloud-devrel%2Fnotebooks%2Fpresubmit/prod%3Acloud-devrel%2Fnotebooks%2Fpresubmit/KOKORO/7d621830-99ef-47f0-94d0-e6e41c249d3a/0/prod%3Acloud-devrel%2Fnotebooks%2Fpresubmit/Targets
) including logs

**To Reproduce**
1. Submit PR that includes a notebook with an `import tensorflow_hub` statement
2. Observe that the notebook run CI test fails

**Expected behavior**
CI test should pass

**Comment by ivanmkc** [comment]
Hi, I've taken over the testing infra. After discussion with other DPEs\TW's, we've decided to test using a minimal dependency image as detailed at go/cloudai-notebook-testing. Let me know if you have more feedback regarding this.
