### ISSUE TITLE
"Failed to create endpoint"

### ISSUE THREAD

**Issue by nataly-obr** [GoogleCloudPlatform/ai-platform-samples#235]
**Describe the bug**
"Failed to create endpoint "new_endpoint"". Can't create an endpoint via AI Platform (Unified) Console.

**What sample is this bug related to?**
I' trying to create and endpoint to deploy text entity extraction model trained with AutoML training method. (Model was created and trained via AI Platform (Unified) Console, Region: "europe-west4 (Netherlands)").

**Source code / logs**

![Screenshot from 2020-12-27 08-55-22](https://user-images.githubusercontent.com/59837137/103164839-5610e300-4821-11eb-89ba-6c52f599baee.png)

**To Reproduce**
1. Go to "AI Platform (Unified)"
2. Go to "Models"
3. Pick a model
4. Go to "Deploy & Test"
5. Click on "Deploy to Endpoint"
6. Opt "Create new endpoint"
7. Input "Endpoint name" (in my case "new_endpoint")
8. Click "Deploy"
9. See error "Failed to create endpoint "new_endpoint""

**Expected behavior**
Endpoint is created and model is deployed

**System Information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.5 LTS

**Comment by shannonphu** [comment]
Hi @nataly-obr Did you manage to resolve this issue? I am running into this while following the tutorials at https://cloud.google.com/ai-platform-unified/docs/tutorials/image-recognition-automl/deploy-predict

**Comment by nataly-obr** [comment]
> Hi @nataly-obr Did you manage to resolve this issue? I am running into this while following the tutorials at https://cloud.google.com/ai-platform-unified/docs/tutorials/image-recognition-automl/deploy-predict

Hi @shannonphu, 
Not exactly resolve, but after I deleted an endpoint that already existed for that region (however, for another model) I was able to create a new endpoint.

**Comment by shannonphu** [comment]
@nataly-obr Interesting, this is my first time using GCP and that was the first endpoint I created. Did you have any issues when creating your first endpoint?

**Comment by nataly-obr** [comment]
@shannonphu No, I didn't.

**Comment by maxzzze** [comment]
Experiencing the same issue but the error seems slightly different now but still uninformative. 

![Screen Shot 2021-05-17 at 12 08 47 PM](https://user-images.githubusercontent.com/24981282/118521177-c523a100-b708-11eb-8f92-6bafaa0466c6.png)

**Comment by shannonphu** [comment]
It seems to be some intermittent issue which I resolved by waiting another day and retrying.

**Comment by jholowaty** [comment]
Hi!!! how can i delete an endpoint was failed in the create step?

![image](https://user-images.githubusercontent.com/89220197/135361918-26044976-be97-4358-a069-cf7dd82348c6.png)

The delete option is gray and we have the permission and action "aiplatform.endpoints.delete". Or maybe we must wait x days until gcp delete it automatically?

Thanks!!

**Comment by kweinmeister** [comment]
Good discussion in this issue. I will go ahead and close it, since it is related to usage of the console, and not an issue with one of the samples in this repo. BTW, we now have the [GoogleCloudPlatform/vertex-ai-samples](https://github.com/GoogleCloudPlatform/vertex-ai-samples) repo, where you can find the latest versions of all Vertex AI samples.
