### ISSUE TITLE
Please update Colab links in notebooks links they give errors

### ISSUE THREAD

**Issue by TechandEco** [GoogleCloudPlatform/ai-platform-samples#236]
Howdy team

When you are looking to visit any of the lovely samples from this tech doc https://cloud.google.com/automl-tables/docs/notebooks under "AutoML notebooks", if you click the first (getting started notebook) or even the last (music recommendation), it successfully takes you to GitHub, but when you click the COLAB link in the ReadMe you get a pop-up error message that says permissions need to be enabled bla bla bla, even if you do. Did a bit of digging and it seems the notebooks moved and the URL to visit that notebook hasn't been updated (no big deal), just whenever you can update them it would be nice so users can visit the awesome samples in Colab.

For example, the [Getting Started notebook](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/notebooks/samples/tables/census_income_prediction/getting_started_notebook.ipynb).

- The "Run in Colab" link points to: https://colab.sandbox.google.com/github/GoogleCloudPlatform/python-docs-samples/blob/master/tables/automl/notebooks/census_income_prediction/getting_started_notebook.ipynb
- The "View in GitHub" link points to: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tables/automl/notebooks/census_income_prediction/getting_started_notebook.ipynb

These are in the `python-docs-samples` repo, but the notebooks now live in the `ai-platform-samples` repo. The new Colab link should be: https://colab.sandbox.google.com/github/GoogleCloudPlatform/ai-platform-samples/blob/master/notebooks/samples/tables/census_income_prediction/getting_started_notebook.ipynb

**Comment by kweinmeister** [comment]
I tested all 4 of the notebooks, and the links are now fixed. Thank you for reporting this issue!
