### ISSUE TITLE
Deploy an explainable model with Integrated Gradients in a global endpoint doesn't support N1 machine-type

### ISSUE THREAD

**Issue by wanderer2019** [GoogleCloudPlatform/ai-platform-samples#242]
**Describe the bug**
The code provided to create the version doesn't work due to the Notebook consider a global endpoint:
# Create the version with gcloud
!gcloud beta ai-platform versions create $IG_VERSION \
--model $MODEL \
--origin $export_path \
--runtime-version 1.15 \
--framework TENSORFLOW \
--python-version 3.7 \
--machine-type n1-standard-4 \
--explanation-method integrated-gradients \
--num-integral-steps 25

ERROR: (gcloud.beta.ai-platform.versions.create) INVALID_ARGUMENT: The specified machine type 'n1-standard-4' is only available on the regional endpoint.

However when the machine-type is changed to "--machine-type mls1-c1-m2 \" which is the proper one as per google documentation, the following error popo up:

ERROR: (gcloud.beta.ai-platform.versions.create) INVALID_ARGUMENT: Field: version.machine_type Error: Unsupported machine type 'mls1-c1-m2' for model explanation, must be Compute Engine machine types, see the full list in https://cloud.google.com/ml-engine/docs/machine-types#compute-engine-machine-types.
- '@type': type.googleapis.com/google.rpc.BadRequest
  fieldViolations:
  - description: Unsupported machine type 'mls1-c1-m2' for model explanation, must
      be Compute Engine machine types, see the full list in https://cloud.google.com/ml-engine/docs/machine-types#compute-engine-machine-types.
    field: version.machine_type

Could you please explain how have you sorted out this issue?

**Comment by kweinmeister** [comment]
I believe that this behavior may have changed after the notebook was created. Have you tried using a regional endpoint with `n1-standard-4`?

**Comment by kweinmeister** [comment]
Hi, as we haven't heard back, we'll go ahead and close the issue. Please free to reopen if you have more information. Thanks.
