### ISSUE TITLE
Delete CustomJob resources at the end of custom_job_image_classification_model_for_online_prediction.ipynb

### ISSUE THREAD

**Issue by alecglassford** [GoogleCloudPlatform/ai-platform-samples#250]
In ai-platform-unified/notebooks/custom_job_image_classification_model_for_online_prediction.ipynb , in the "Cleaning up" section, add code to delete the CustomJob resources that got created in the notebook.

See comment in https://github.com/GoogleCloudPlatform/ai-platform-samples/pull/248#pullrequestreview-610300427

**Comment by andrewferlitsch** [comment]
This appears to have been fixed with PR 248
