### ISSUE TITLE
Error when changing region to europe-west4 on XAI notebook

### ISSUE THREAD

**Issue by rafaelsf80** [GoogleCloudPlatform/ai-platform-samples#293]
HI,
I try to run the [explainable AI notebook](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/unofficial/sdk/AI_Platform_(Unified)_SDK_Explainable_AI_Custom_Tabular.ipynb), and it runs successfully with Colab on `us-central1`. However, changing region to `europe-west4` (and GPU type to T4, since K80 is not supported in that region) raises a 400 Internal error on `model.deploy`.
Thanks,

**Comment by kweinmeister** [comment]
Hi. Update: we now have the latest explainable AI notebooks in this [folder](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/master/notebooks/official/explainable_ai) in the `vertex-ai-samples` repo. If you are still seeing the issue with one of those notebooks, please file an issue on that repo.
