### ISSUE TITLE
None of the colab links work.  Errors out. 

### ISSUE THREAD

**Issue by stevewalker-de** [GoogleCloudPlatform/ai-platform-samples#297]
Click on 'Run in Colab'.  Errors with:
![image](https://user-images.githubusercontent.com/67876607/116641290-073f9b00-a932-11eb-84a3-640d48ac498a.png)

**Comment by stevewalker-de** [comment]
Authorized with Github, same result.

**Comment by stevewalker-de** [comment]
You can download the ipynb, and then upload to colab, but I didn't think that was the intent with the link.

**Comment by kweinmeister** [comment]
Verified as fixed in https://github.com/GoogleCloudPlatform/ai-platform-samples/commit/2c9d75b1de1fd17ef7756f58653fdf0fd27cbf80
