### ISSUE TITLE
In two places pip is used instead of pip3 

### ISSUE THREAD

**Issue by JoshuaFox** [GoogleCloudPlatform/ai-platform-samples#306]
1. In `gapic-custom-image-classification-online` `pip3` is generally used. This is correct. In two places `pip` is used. I suspect that in some machines, `pip` is an alias of `pip3` which is why this worked, but in my Mac, that is not the case.
2. [ I created a PR](  https://github.com/GoogleCloudPlatform/ai-platform-samples/pull/305) but need permissions to run the workflow to proceed. Also, it says that a Google contributor agreement is needed, but one exists: It was created when I contributed to a different Google repo.

**Comment by kweinmeister** [comment]
Fixed in #305
