### ISSUE TITLE
`pip install -r requirements.txt' shows an error, after another `python setup.py install`

### ISSUE THREAD

**Issue by happyhuman** [GoogleCloudPlatform/ai-platform-samples#31]
1- Created a new clean virtual env with python3.
2- Went to quickstart sample and ran python setup.py install
3- Went to sklearn base sample and ran pip install -r requirements.txt and got that error again.
4- in sklearn base sample, this time I ran python setup.py install and it worked fine.

It may be a good idea to just choose either setup.py, or requirements.txt and remove the other.

**Comment by gogasca** [comment]
Updated it requirements.txt to use setup.py definition
