### ISSUE TITLE
Feature store notebook Api documentation links are returning 404

### ISSUE THREAD

**Issue by jessikad-google** [GoogleCloudPlatform/ai-platform-samples#343]
**Describe the bug**
All references to Feature Store API documentation links are returning 404 in the following notebook

**What sample is this bug related to?**
https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/feature_store/gapic-feature-store.ipynb

**Source code / logs**

"source": [
        "You can use [GetFeaturestore](https://cloud.google.com/ai-platform-unified/featurestore/docs/reference/rpc/google.cloud.aiplatform.v1beta1#google.cloud.aiplatform.v1beta1.FeaturestoreService.GetFeaturestore) or [ListFeaturestores](https://cloud.google.com/ai-platform-unified/featurestore/docs/reference/rpc/google.cloud.aiplatform.v1beta1#google.cloud.aiplatform.v1beta1.FeaturestoreService.ListFeaturestores) to check if the Featurestore was successfully created. The following example gets the details of the Featurestore.\n"
      ]

"While the [ListFeatures](https://cloud.google.com/ai-platform-unified/featurestore/docs/reference/rpc/google.cloud.aiplatform.v1beta1#google.cloud.aiplatform.v1beta1.FeaturestoreService.ListFeatures) method allows you to easily view all features of a single\n",
        "entity type, the [SearchFeatures](https://cloud.google.com/ai-platform-unified/featurestore/docs/reference/rpc/google.cloud.aiplatform.v1beta1#google.cloud.aiplatform.v1beta1.FeaturestoreService.SearchFeatures) method searches across all featurestores\n",

        "[Online Serving APIs](https://cloud.google.com/ai-platform-unified/featurestore/docs/reference/rpc/google.cloud.aiplatform.v1beta1#featurestoreonlineservingservice)\n",
        "lets you serve feature values for small batches of entities. It's designed for latency-sensitive service, such as online model prediction. For example, for a movie service, you might want to quickly shows movies that the current user would most likely watch by using online predictions."

**To Reproduce**
1. Go to 'https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/feature_store/gapic-feature-store.ipynb'
2. Click on  'GetFeaturestore', 'ListFeaturestores',  'ListFeatures',  'SearchFeatures' or 'Online Serving APIs' links
3. See 404 error

**Expected behavior**
Expect to see correct API Documentation link which I have yet to find

**Comment by kweinmeister** [comment]
The latest version of this notebook is in the `vertex-ai-samples` repo [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/official/feature_store/gapic-feature-store.ipynb).

I did a quick test of the links, and they appear to have been fixed. Please reopen in that repo if you are still seeing this issue. Thank you!
