### ISSUE TITLE
Error "DataFrame constructor not properly called!"

### ISSUE THREAD

**Issue by Ayo-faks** [GoogleCloudPlatform/ai-platform-samples#371]

**Comment by kweinmeister** [comment]
Hi, can you please point us to the code in this sample repo this issue is related to?

**Comment by andrewferlitsch** [comment]
@Ayo-faks can you please point us to the code in this sample repo this issue is related to?

**Comment by kweinmeister** [comment]
Closing this issue, as there isn't enough info to proceed. Please feel free to reopen if you can point us to sample code which we can help fix.
