### ISSUE TITLE
Pipeline with AutoML and Tabular Data notebook opening error

### ISSUE THREAD

**Issue by vochicong** [GoogleCloudPlatform/ai-platform-samples#372]
The notebook can not be opened on GitHub, nbviewer, VSCode, Jupyter ... due to some JSON error.

- https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/unofficial/pipelines/google-cloud-pipeline-components_automl_tabular.ipynb
- https://nbviewer.jupyter.org/github/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/unofficial/pipelines/google-cloud-pipeline-components_automl_tabular.ipynb

**Comment by ivanmkc** [comment]
This was fixed and files are moved to the official folders now. Thanks for flagging.
