### ISSUE TITLE
Notebook uses BQ datasource from invalid location

### ISSUE THREAD

**Issue by ivanmkc** [GoogleCloudPlatform/ai-platform-samples#385]
This notebook has a problem with the dataset.

https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/pipelines/automl_tabular_classification_beans.ipynb

This: "bq://aju-dev-demos.beans.beans1"

**Comment by kweinmeister** [comment]
The latest version of this pipeline is now in the `vertex-ai-samples` repo [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/official/pipelines/automl_tabular_classification_beans.ipynb). If there are still issues with the dataset, we can file an issue in that repo.
