### ISSUE TITLE
GPU Underutilization for AI-platform-samples Training

### ISSUE THREAD

**Issue by stevenzhang-support** [GoogleCloudPlatform/ai-platform-samples#386]
**Describe the bug**
My user reported that when they are aiming to train object detection models using the TensorFlow Object Detection API on Google Cloud Platform using V100 GPUs. The GPU resource is underutilized when training on GCP but fully utilized when training on a local AWS EC2 or GCE VM instance. The speed difference is orders of magnitude slower, preventing us from feasibly using GCP to run large training jobs for production.

Addition case is that When user trained on the GCE VM ( n1-standard-8) with 1 NVIDIA TESLA P100 GPU, the training time is around 1 minute per epoch (there are 50 epochs for training the model). However, when I submit the training job through gcloud ai-platform, with the same setup of n1-standard-8 and 1 NVIDIA TESLA P100 GPU, it takes 3 hours per epoch.

**What sample is this bug related to?**
When I used a sample from [1] I can reproduce this as I found the GPU usage was really low from AI platform GPU usage metrics wI made sure the container used in training was built for GPU purposes [2]. Due to the low GPU was also found using sample code [1], I open the issue in this repo.

**Current behaviour:** When training on a physical instance with GPU, the GPU can reach a high usage rate. But when training was launched on an AI platform the GPU usage rate was unbelievably low.

[1] https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/training/pytorch/structured/python_package#run-on-gpu
[2] gcr.io/cloud-ml-public/training/pytorch-gpu.1-4

**Source code / logs**
Source code: https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/training/pytorch/structured/python_package

**To Reproduce**
1. Go to [1] to follow the steps to train this code sample on AI platform using GPU
2. The training finished without error but the GPU usage rate is 1% throughout the training duration.

**Expected Behaviour:** The training on AI platforms can also achieve reasonably high GPU usage rate.

**System Information**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: AI platform on GCP
- **Framework and version (Tensorflow, scikit-learn, XGBoost)**:  Pytorch (Tensorflow too)
- **Python version**: 3.7
- **Exact command to reproduce**:
- **Tensorflow Transform environment (if applicable, see below)**:

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
```
**Additional context**
N/A

**Comment by kweinmeister** [comment]
This repo is for issues with the sample code. If there is an issue with the AI Platform Training service itself, please work with the AI Platform Training team (showing them this sample if needed). Please feel free to reopen the issue if you have more questions.
