### ISSUE TITLE
Internal Server 500 Error

### ISSUE THREAD

**Issue by bdoohan** [GoogleCloudPlatform/ai-platform-samples#387]
**Describe the bug**
When running [this notebook](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/unofficial/matching_engine/matching_engine_for_indexing.ipynb) I get to the cell with the following code:

` INDEX_RESOURCE_NAME = ann_index.result().name
INDEX_RESOURCE_NAME`

This is giving me a 500 Error: 

`<ipython-input-66-af83f87d0e5f> in <module>
----> 1 INDEX_RESOURCE_NAME = ann_index.result().name
      2 INDEX_RESOURCE_NAME

/opt/conda/lib/python3.7/site-packages/google/api_core/future/polling.py in result(self, timeout, retry)
    132             # pylint: disable=raising-bad-type
    133             # Pylint doesn't recognize that this is valid in this case.
--> 134             raise self._exception
    135 
    136         return self._result

    [... skipping hidden 1 frame]

<ipython-input-63-af83f87d0e5f> in <module>
----> 1 INDEX_RESOURCE_NAME = ann_index.result().name
      2 INDEX_RESOURCE_NAME

/opt/conda/lib/python3.7/site-packages/google/api_core/future/polling.py in result(self, timeout, retry)
    132             # pylint: disable=raising-bad-type
    133             # Pylint doesn't recognize that this is valid in this case.
--> 134             raise self._exception
    135 
    136         return self._result

InternalServerError: 500 INTERNAL`

**What sample is this bug related to?**

[https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/ai-platform-unified/notebooks/unofficial/matching_engine](https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/ai-platform-unified/notebooks/unofficial/matching_engine)

**Source code / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**To Reproduce**
1. Go to 'https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/ai-platform-unified/notebooks/unofficial/matching_engine'
2. Run all lines of code until `INDEX_RESOURCE_NAME = ann_index.result().name`
3. See error

**Expected behavior**
Instance is created without error

**System Information**
machine:  x86_64 version:  #1 SMP Debian 4.19.181-1 (2021-03-19) platform:  Linux-4.19.0-16-cloud-amd64-x86_64-with-debian-10.10 uname:  uname_result(system='Linux', node='python-20210627-223300', release='4.19.0-16-cloud-amd64', version='#1 SMP Debian 4.19.181-1 (2021-03-19)', machine='x86_64', processor='') system:  Linux processor:  

To obtain the Tensorflow and Tensorflow Transform environment do

```
pip freeze |grep tensorflow
pip freeze |grep apache-beam
```
**Additional context**

**Comment by kweinmeister** [comment]
The latest version of this notebook is now in the `vertex-ai-samples` repo [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/community/matching_engine/matching_engine_for_indexing.ipynb). Please let us know if you are still seeing this problem by filing an issue in that repo.

**Comment by kweinmeister** [comment]
Thanks again for your issue. We'll go ahead and close the issue here. Please feel free to reopen an issue in the `vertex-ai-samples` repo, if you are still seeing the problem in the latest version of the notebook.
