### ISSUE TITLE
Runtime version 1.14 update

### ISSUE THREAD

**Issue by gogasca** [GoogleCloudPlatform/ai-platform-samples#40]
Update to runtime version and TF 1.14 https://cloud.google.com/ml-engine/docs/tensorflow/runtime-version-list

**Comment by fisakhan** [comment]
Is there any plan for a runtime version that supports TF 2.0?

**Comment by gogasca** [comment]
> Is there any plan for a runtime version that supports TF 2.0?

We are working in new samples, please stay tuned @padominguez FYI

**Comment by gogasca** [comment]
> Is there any plan for a runtime version that supports TF 2.0?

We are planning to release support very soon. You can use as workaround custom containers for training with 2.0

**Comment by gogasca** [comment]
@fisakhan Please check it https://cloud.google.com/ai-platform/docs/release-notes

**Comment by gogasca** [comment]
@fisakhan we updated our new samples here please take a look [here](https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/training/tensorflow/census/tf-keras)
