### ISSUE TITLE
Incorrect way to remove contents of a bucket?

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/ai-platform-samples#407]
**Describe the bug**

Instead of clearing the contents of a bucket, the below-mentioned notebook deletes an entire bucket. 

**What sample is this bug related to?**

`matching_engine_for_indexing.ipynb`

**Source code / logs**

Currently, the notebook uses `! gsutil rm -rf {BUCKET_NAME}`. Isn't it supposed to remove the entire bucket when the expected action is "NOTE: Everything in this GCS DIR will be DELETED before uploading the data."?

**Comment by kweinmeister** [comment]
This repo is going to be archived, and we are redirecting our users to the [Vertex AI Samples repo](https://github.com/GoogleCloudPlatform/vertex-ai-samples). Please feel free to reopen this issue in that repo, if you would like to discuss it further.
