### ISSUE TITLE
Improvement suggestions for the ANN sample notebook

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/ai-platform-samples#408]
Notebook I am referring to: `matching_engine_for_indexing.ipynb`. Here, I would like to share a few observations while I was working through the tutorial and some potential improvement suggestions. 

* Under the "Create Indexes" section, it mentions 

  > Please read the documentation to understand the various configuration parameters that can be used to tune the index

  I think it might be more complete if "documentation" was actually hyperlinked. 

* Under the "Create Brute Force Index (for Ground Truth)" section, it mentions

  > To ensure an apples to apples comparison, the distanceMeasureType and featureNormType, dimensions of the brute force index should match those of the production indices being tuned.

  But we never used `featureNormType` until and unless I'm missing something:

```python
treeAhConfig = struct_pb2.Struct(
    fields={
        "leafNodeEmbeddingCount": struct_pb2.Value(number_value=500),
        "leafNodesToSearchPercent": struct_pb2.Value(number_value=7),
    }
)

algorithmConfig = struct_pb2.Struct(
    fields={"treeAhConfig": struct_pb2.Value(struct_value=treeAhConfig)}
)

config = struct_pb2.Struct(
    fields={
        "dimensions": struct_pb2.Value(number_value=DIMENSIONS),
        "approximateNeighborsCount": struct_pb2.Value(number_value=150),
        "distanceMeasureType": struct_pb2.Value(string_value="DOT_PRODUCT_DISTANCE"),
        "algorithmConfig": struct_pb2.Value(struct_value=algorithmConfig),
    }
)

metadata = struct_pb2.Struct(
    fields={
        "config": struct_pb2.Value(struct_value=config),
        "contentsDeltaUri": struct_pb2.Value(string_value=BUCKET_NAME),
    }
)

ann_index = {
    "display_name": DISPLAY_NAME,
    "description": "Glove 100 ANN index",
    "metadata": struct_pb2.Value(struct_value=metadata),
}
```
* There's no real description about how one should derive the test embeddings. We are creating an artificial array for test purposes. I think it might be beneficial for both the readers and the customers to have a proper description of what's expected during a real production use-case i.e. one should first compute the embeddings and then make the call. Ideally, I'd want that to be in the notebook itself. 
* I think we are using the ANN index for testing purposes. Would be helpful to add a note on that. Also, what are the most important parameters a user should care about while creating the proto? 
* How do I parse the response?

**Comment by kweinmeister** [comment]
This repo is going to be archived, and we are redirecting our users to the [Vertex AI Samples repo](https://github.com/GoogleCloudPlatform/vertex-ai-samples). Please feel free to reopen this issue in that repo, if you would like to discuss it further.
