### ISSUE TITLE
_InactiveRpcError of RPC when running `matching_engine_for_indexing.ipynb` 

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/ai-platform-samples#409]
**Describe the bug**

I've followed the steps outlined in the `matching_engine_for_indexing.ipynb` notebook. Differences include: I used `us-east4` as opposed to central and I did not compute the brute-force indexes because I did not want to compute the recall. 

**What sample is this bug related to?**

`matching_engine_for_indexing.ipynb`

**Source code / logs**

```
---------------------------------------------------------------------------
_InactiveRpcError                         Traceback (most recent call last)
/tmp/ipykernel_30367/467153318.py in <module>
    108     request.float_val.append(val)
    109 
--> 110 response = stub.Match(request)
    111 response

~/.local/lib/python3.7/site-packages/grpc/_channel.py in __call__(self, request, timeout, metadata, credentials, wait_for_ready, compression)
    944         state, call, = self._blocking(request, timeout, metadata, credentials,
    945                                       wait_for_ready, compression)
--> 946         return _end_unary_response_blocking(state, call, False, None)
    947 
    948     def with_call(self,

~/.local/lib/python3.7/site-packages/grpc/_channel.py in _end_unary_response_blocking(state, call, with_call, deadline)
    847             return state.response
    848     else:
--> 849         raise _InactiveRpcError(state)
    850 
    851 

_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1626924716.617165762","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3008,"referenced_errors":[{"created":"@1626924716.617160400","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
```

**To Reproduce**

Here's my notebook: 
[matching_engine_for_indexing.ipynb.zip](https://github.com/GoogleCloudPlatform/ai-platform-samples/files/6859842/matching_engine_for_indexing.ipynb.zip)

**Comment by mlegore** [comment]
I have also experienced this issue while prototyping with this product. Hoping we can resolve it.

**Comment by kweinmeister** [comment]
We have the latest version of the notebook in the `vertex-ai-samples` repo [here](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/community/matching_engine/matching_engine_for_indexing.ipynb).

There is currently a similar discussion in [issue 118](https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/118) in that repo.

**Comment by kweinmeister** [comment]
Closing the issue here. If this is still an issue, please file an issue in the `vertex-ai-samples` repo. Thank you!
