### ISSUE TITLE
Incorrect Colab link

### ISSUE THREAD

**Issue by sayakpaul** [GoogleCloudPlatform/ai-platform-samples#410]
@nikitamaia the Colab Notebook link is incorrect here `distributed-hyperparameter-tuning.ipynb`. 

Also, `docker` won't run on Colab.

**Comment by kweinmeister** [comment]
Good catch @sayakpaul. The notebook is being maintained in its new location at https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/community/hyperparameter_tuning/distributed-hyperparameter-tuning.ipynb. We can file an issue in that repo if we still see the issue with that one.
