### ISSUE TITLE
Data Analysis on Cash payments seems confusing.

### ISSUE THREAD

**Issue by andrewferlitsch** [GoogleCloudPlatform/ai-platform-samples#43]
This description in the README for Datasets I found a distraction and confusing:

**Dataset Analysis**
The goal is to train a Binary Classification model that predicts whether a person leaves 20% tips or more (target label) based on the taxi ride information.

We did some analysis of the dataset and realized that over 50% of the payment types are Cash. We also noticed that the majority of cash payments don't have any tips. We believe this is because the tips for cash payments have not been properly recorded, and therefore, the dataset is somewhat incomplete for cash payments.

This will naturally have an impact on any trained model. The model accuracy for non-cash payments will be a bit lower than the general accuracy. On the other hand, any prediction of the model for cash payments is not as reliable as the other payment types.

*Recommendation*

I recommend either:

1. Just say the majority of tips for cash payment were not recorded and make no statement on general accuracy; other than it will be biased towards predicting the tip < 20%, or
2. Make a 3rd dataset that has no cash payments, or
3. Synthesize values for the cash tips from the non-cash distribution.

**Comment by gogasca** [comment]
Hi Andrew, would you mind taking a stab on this via a PR ?

**Comment by andrewferlitsch** [comment]
These datasets are for demonstrating Vertex (AI Platform) AI. As long as they worked, which this one does, they accuracy and quality are not an issue. I am closing this bug.
