### ISSUE TITLE
ai-platform-samples/notebooks/

### ISSUE THREAD

**Issue by andrewferlitsch** [GoogleCloudPlatform/ai-platform-samples#46]
I don't understand the relevance of the section on notebooks. Not clear from reading the README whom the targeted audience would be. Seems to the ordinary MLE and Data Scientist would not use anything in this section.

**Comment by gogasca** [comment]
These are mainly tools for the AI Platform notebooks created by Slava and his team.

**Comment by gogasca** [comment]
We created this section to host notebooks as well.
