### ISSUE TITLE
Tensorboard NB is misisng

### ISSUE THREAD

**Issue by bdoohan-goog** [GoogleCloudPlatform/ai-platform-samples#490]
**Describe the bug**
Notebook is missing and is replaced with this: [https://github.com/GoogleCloudPlatform/ai-platform-samples/blame/master/ai-platform-unified/notebooks/official/tensorboard/remove_this_placeholder_after_first_file_is_commited](https://github.com/GoogleCloudPlatform/ai-platform-samples/blame/master/ai-platform-unified/notebooks/official/tensorboard/remove_this_placeholder_after_first_file_is_commited)

Shouldn't there be a notebook here?

**Comment by kweinmeister** [comment]
The content within the `ai-platform-unified` folder has been moved to https://github.com/GoogleCloudPlatform/vertex-ai-samples

I would recommend looking at this notebook for TensorBoard: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/master/notebooks/community/ml_ops/stage2/get_started_vertex_tensorboard.ipynb

**Comment by kweinmeister** [comment]
I'll close this issue here. Please feel free to reopen in the `vertex-ai-samples` repo if you have more questions on this.
