### ISSUE TITLE
Incomplete instructions in the Prerequisites section 

### ISSUE THREAD

**Issue by happyhuman** [GoogleCloudPlatform/ai-platform-samples#51]
The last item in the Prerequisites section in this [README](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/training/pytorch/structured/custom_containers/base/README.md) is incomplete.  There should be something after "Change the directory to this sample and run"

**Comment by nnegrey** [comment]
I'll remove the `and run` because it doesn't make sense for them to do anything else since it all runs inside a docker image.

**Comment by happyhuman** [comment]
Makes sense.   :)

**Comment by nnegrey** [comment]
Only for kokoro to run tests.
