### ISSUE TITLE
Sample not cleaning up after itself

### ISSUE THREAD

**Issue by leahecole** [GoogleCloudPlatform/ai-platform-samples#513]
https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/ai-platform-unified/notebooks/official/explainable_ai/gapic-custom_tabular_regression_online_explain.ipynb

Is leaving buckets behind - I need help debugging the notebooks regular testing job to find helpful error messaging so we can figure out the root cause and hopefully stop the buildup of buckets

This issue replaces https://github.com/googleapis/python-aiplatform/issues/764

**Comment by kweinmeister** [comment]
Hi @leahecole, as @aribray mentioned in https://github.com/googleapis/python-aiplatform/issues/764, the notebook itself can fail, and won't clean up the bucket (and potentially other Cloud resources). AFAIK, there isn't any kind of post-execution hook to guarantee that certain code is run at the end.

If we can track down the `python-docs-samples` test case that is running the notebook, then we may be able to resolve that issue there. For example, we can remove buckets matching `gs://python-docs-samples-testsaip-*` in a teardown step.

**Comment by leahecole** [comment]
Hey @kweinmeister! So normally looking for a `python-docs-samples` test case is a path I would take for any other test, but afaik, the notebook testing procedure for this repo is different than for other repos and until recently I haven't had much insight into it. A few questions

1) Can there be a post execution hook cleanup step that runs as part of the test suite if the tests are known to be leaky?
2) If not, this might be a case for using the reaper bot the CAIIS team put together in the past, and we document what the bot is cleaning up in a central location so that we don't replicate leaky test patterns in the future without also configuring the bot as cleanup. (we may also want to consider a prefix to the name of the bucket like `temp` but I don't want to get too deep in implementation)

**Comment by kweinmeister** [comment]
Yes, sorry, this issue shouldn't tie into `python-docs-samples` tests in any way, I got distracted by the bucket name 😆.

Those are good options to look into. I suspect that #2 might be the best option, but let's see what @ivanmkc thinks.

**Comment by leahecole** [comment]
Ha - no worries - I know - it's confusing because they do use the same underlying test project! Keep me posted @ivanmkc - we can touch base post learning days to figure out if reaper is a good fit, and if so, how to implement it so that I, the other sample owners, and other DPEs in this space would be able to figure out in the future that whatever config we add is to clean up after this particular thing

**Comment by ivanmkc** [comment]
Here are two ideas:

1. Find all buckets created by a user (reserved for testing) and periodically delete them. Not sure if it's possible to identify bucket creators though.

2. Inject a BUCKET_NAME variable to notebooks and have the test infra clean them up even if notebook fails. This may require changes to the notebooks. Authors might also ignore the variable and just their own name.

For Option 1, here's my attempt to get creator information for a given bucket. No luck yet.
```
gsutil ls -L -b gs://ivanmkc-test2
gs://ivanmkc-test2/ :
        Storage class:                  STANDARD
        Location type:                  region
        Location constraint:            US-CENTRAL1
        Versioning enabled:             None
        Logging configuration:          None
        Website configuration:          None
        CORS configuration:             None
        Lifecycle configuration:        None
        Requester Pays enabled:         None
        Labels:                         None
        Default KMS key:                None
        Time created:                   Thu, 25 Feb 2021 23:09:39 GMT
        Time updated:                   Thu, 25 Feb 2021 23:09:39 GMT
        Metageneration:                 1
        Bucket Policy Only enabled:     False
        Public access prevention:       inherited
        ACL:
          [
            {
              "entity": "project-owners-1012616486416",
              "projectTeam": {
                "projectNumber": "1012616486416",
                "team": "owners"
              },
              "role": "OWNER"
            },
            {
              "entity": "project-editors-1012616486416",
              "projectTeam": {
                "projectNumber": "1012616486416",
                "team": "editors"
              },
              "role": "OWNER"
            },
            {
              "entity": "project-viewers-1012616486416",
              "projectTeam": {
                "projectNumber": "1012616486416",
                "team": "viewers"
              },
              "role": "READER"
            }
          ]
        Default ACL:
          [
            {
              "entity": "project-owners-1012616486416",
              "projectTeam": {
                "projectNumber": "1012616486416",
                "team": "owners"
              },
              "role": "OWNER"
            },
            {
              "entity": "project-editors-1012616486416",
              "projectTeam": {
                "projectNumber": "1012616486416",
                "team": "editors"
              },
              "role": "OWNER"
            },
            {
              "entity": "project-viewers-1012616486416",
              "projectTeam": {
                "projectNumber": "1012616486416",
                "team": "viewers"
              },
              "role": "READER"
            }
          ]
```

**Comment by kweinmeister** [comment]
This repo is going to be archived, and we are redirecting our users to the [Vertex AI Samples repo](https://github.com/GoogleCloudPlatform/vertex-ai-samples). Please feel free to reopen this issue in that repo, if you would like to discuss it further.
