### ISSUE TITLE
How are Kaggle Notebooks selected?

### ISSUE THREAD

**Issue by ucalyptus** [GoogleCloudPlatform/ai-platform-samples#66]
**Is your feature request related to a problem? Please describe.**
I am curious if Kaggle NB requests can be taken or not. Obviously it will be subject to review.

**Describe the solution you'd like**
Propose a community entry for Kaggle NBs for [AI Hub](https://aihub.cloud.google.com/).

**Key technologies to include**
* Workflow (Training, Serving, Complete Guide):
* AI Platform specfic features (CPU, GPU, HP Tuning, TPU):
* Framework (Tensorflow, Keras, scikit-learn, XGBoost, ...):
* Model:
* Dataset:

**Additional context**
None

**Comment by gogasca** [comment]
@ucalyptus Sorry for the late response, can you provide an example of a Kaggle notebook request? 
That will help me understand better what are you referring to

**Comment by ucalyptus** [comment]
@gogasca As in the AIHub website under section **Learn using a selection of the best notebooks from the Kaggle community** I want to propose a notebook on Histopathological Cancer Detection.
Here is the [Notebook](https://www.kaggle.com/sayantandas30011998/fastai-v1-densenet201) where we got an AUC score of 0.96 and were 138th in the Public LB .

**Comment by gogasca** [comment]
My understanding is that Kaggle NB live in Kaggle https://www.kaggle.com/kernels, we do accept Notebooks, but they should be compatible with our AI Platform Notebooks product. Check our [contribution guidelines](https://github.com/GoogleCloudPlatform/ai-platform-samples/blob/master/CONTRIBUTING.md#notebook-contributions).

**Comment by ucalyptus** [comment]
got it
