### ISSUE TITLE
Tensorflow 2 Examples

### ISSUE THREAD

**Issue by faroit** [GoogleCloudPlatform/ai-platform-samples#86]
This repository does not contain any tensorflow 2 examples. Since TF2 seems to be a supported product on GCP, it would be great if at least the quickstart guide could be updated.

**Comment by gogasca** [comment]
Hi Faroit,
Yes, we support TF 2.x in Deep Learning VMs, Deep Learning containers and AI Platform Training via Docker containers. Our team is working as we speak in generating samples for TF 2.x.
I will keep this issue open and update it once we release the first set of them.

**Comment by gogasca** [comment]
Please check it: https://cloud.google.com/ai-platform/docs/release-notes
We will update samples soon

**Comment by gogasca** [comment]
@faroit we updated our new samples [here](https://github.com/GoogleCloudPlatform/ai-platform-samples/tree/master/training/tensorflow/census/tf-keras) please take a look

**Comment by faroit** [comment]
@gogasca thanks for the update. I had a intensive look 👍
